### ISSUE TITLE
`ddave-v0` error in *some* solutions

### ISSUE THREAD

**Issue by gallorob** [amidos2006/pcg_benchmark#2]
An `IndexError` is raised when evaluating solutions' diversity. This is often the case with `ga` and `es` generators, `random` never raises the error.

**Minimal code for reproducibility**:
```
import generators.ga
import pcg_benchmark

env = pcg_benchmark.make('ddave-v0')

generator = generators.ga.Generator(env)
generator.reset(**{'fitness': 'quality_control_diversity'})

for i in range(100):
    print(f"  Iteration {i}: {generator.best():.2f}")
    generator.update()
```
Then attach a debugger and wait for it to crash 🤷‍♂️

**Likely cause:**
It seems the solution in `info` is not accurate, which then leads to an `IndexError` when reconstructing it. Particularly, the `x` and `y` values in the first element of the `solution` list are not the same as in `player_locations`.

**Comment by amidos2006** [comment]
content that cause the issue
```python
from pcg_benchmark import make

env = make('ddave-v0')
lvl = [[1,0,1,0,6,1,2,1,0,0,4],
[4,0,4,6,4,6,6,0,1,6,0],
[0,6,1,4,1,1,4,6,0,0,6],
[1,1,1,4,0,4,0,4,6,0,1],
[0,0,3,0,0,1,1,5,0,6,6],
[0,0,0,4,6,1,6,6,1,1,6],
[1,0,1,0,1,1,0,4,6,4,6]]
env.info(lvl)
```

![broken_lvl](https://github.com/user-attachments/assets/3c14de08-81a6-4d3c-af90-a9bbe6ae3297)

**Comment by amidos2006** [comment]
solved in https://github.com/amidos2006/pcg_benchmark/commit/5cb97a8fd4b7be1a6d62f1ae1844e3f0df148a17
